
from . import res_users
from . import sections
from . import res_partner
from . import insurance_contract
from . import product
from . import clinics
from . import doctors
from . import surgeries
from . import rooms
from . import inpatient
from . import clinic_visit
from . import laboratory
from . import radiology
from . import reception
from . import res_company
from . import hospital_config
from . import sale_order
from . import catheterization
from . import product_access
from . import surgery_room
from . import lab_to_lab
from . import account_payment_cash
#from . import hospital_dashboard
